version: '3.4'

services:

  sqldata:
   image: "mcr.microsoft.com/mssql/server:2017-latest"

  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: FileShare.MVC/Dockerfile
    depends_on:
      - sqldata
